<?php

return [
    'sf1' => [
        'code' => 'SF1',
        'number' => '1',
        'name' => 'School Register',
        'title' => 'SF1 School Register',
        'live' => true,
        'description' => 'School Form 1 (SF1) School Register for learner profiles, class master lists, enrolment status, parent information, and adviser-ready DepEd reporting.',
    ],
    'sf2' => [
        'code' => 'SF2',
        'number' => '2',
        'name' => 'Daily Attendance Report of Learners',
        'title' => 'SF2 Daily Attendance Report of Learners',
        'live' => true,
        'description' => 'School Form 2 (SF2) Daily Attendance Report of Learners with QR attendance, absence tracking, monthly summaries, and print-ready DepEd layout.',
    ],
    'sf3' => [
        'code' => 'SF3',
        'number' => '3',
        'name' => 'Books Issued and Returned',
        'title' => 'SF3 Books Issued and Returned',
        'live' => true,
        'description' => 'School Form 3 (SF3) Books Issued and Returned for textbook distribution, returned books, lost copies, and class adviser accountability.',
    ],
    'sf4' => [
        'code' => 'SF4',
        'number' => '4',
        'name' => 'Monthly Learner Movement and Attendance',
        'title' => 'SF4 Monthly Learner Movement and Attendance',
        'live' => false,
        'description' => 'School Form 4 (SF4) related learner movement and attendance reporting context for DepEd school form automation.',
    ],
    'sf5' => [
        'code' => 'SF5',
        'number' => '5',
        'name' => 'Report on Promotion and Level of Proficiency',
        'title' => 'SF5 Report on Promotion and Level of Proficiency',
        'live' => true,
        'description' => 'School Form 5 (SF5) Report on Promotion and Level of Proficiency for end-of-school-year promotion, retention, proficiency, and learner outcomes.',
    ],
    'sf6' => [
        'code' => 'SF6',
        'number' => '6',
        'name' => 'Summarized Report on Promotion and Learning Progress',
        'title' => 'SF6 Summarized Report on Promotion and Learning Progress',
        'live' => false,
        'description' => 'School Form 6 (SF6) summarized promotion and learning progress reporting context for DepEd school forms.',
    ],
    'sf7' => [
        'code' => 'SF7',
        'number' => '7',
        'name' => 'School Personnel Assignment List and Basic Profile',
        'title' => 'SF7 School Personnel Assignment List and Basic Profile',
        'live' => false,
        'description' => 'School Form 7 (SF7) personnel assignment and school staff profile reporting context for DepEd school forms.',
    ],
    'sf8' => [
        'code' => 'SF8',
        'number' => '8',
        'name' => 'Learner Basic Health and Nutrition Report',
        'title' => 'SF8 Learner Basic Health and Nutrition Report',
        'live' => true,
        'description' => 'School Form 8 (SF8) Learner Basic Health and Nutrition Report for adviser-managed height, weight, BMI, nutritional status, and health records.',
    ],
    'sf9' => [
        'code' => 'SF9',
        'number' => '9',
        'name' => 'Learner Progress Report Card',
        'title' => 'SF9 Learner Progress Report Card',
        'live' => true,
        'description' => 'School Form 9 (SF9) Learner Progress Report Card, formerly Form 138, generated from learner grades, values, and quarterly ratings.',
    ],
    'sf10' => [
        'code' => 'SF10',
        'number' => '10',
        'name' => 'Learner Permanent Academic Record',
        'title' => 'SF10 Learner Permanent Academic Record',
        'live' => true,
        'description' => 'School Form 10 (SF10) Learner Permanent Academic Record, formerly Form 137, for permanent scholastic records and learner history.',
    ],
];
